"""
Run hyperparameter search for image-based risk regression models.

This script searches learning rate and weight decay values for ResNet-18 and
ViT-Tiny before final multi-seed training. It expects the dataset generated by
the simulation pipeline:

    data/generated_dataset/
        trial_summary_all.csv
        layout_images/

Only clean-success trials are used for model selection. Splits are made at the
layout level to prevent image variants from the same layout appearing in both
training and validation data.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
import time
from pathlib import Path


np = None
pd = None
Image = None
torch = None
nn = None
optim = None
transforms = None
models = None
timm = None


def parse_float_list(value: str) -> list[float]:
    values = [float(part.strip()) for part in value.split(",") if part.strip()]
    if not values:
        raise argparse.ArgumentTypeError("Provide at least one numeric value.")
    return values


def load_libraries(require_timm: bool = False) -> None:
    """Import heavy ML libraries after CLI parsing so --help stays lightweight."""
    global np, pd, Image, torch, nn, optim, transforms, models, timm

    try:
        import numpy as np_module
        import pandas as pd_module
        from PIL import Image as image_module
        import torch as torch_module
        from torch import nn as nn_module
        from torch import optim as optim_module
        from torchvision import models as models_module
        from torchvision import transforms as transforms_module
    except ModuleNotFoundError as exc:
        raise SystemExit(
            f"Missing dependency: {exc.name}. Install the project requirements "
            "before running hyperparameter search."
        ) from exc

    np = np_module
    pd = pd_module
    Image = image_module
    torch = torch_module
    nn = nn_module
    optim = optim_module
    transforms = transforms_module
    models = models_module

    if require_timm:
        try:
            import timm as timm_module
        except ModuleNotFoundError as exc:
            raise SystemExit(
                "Missing dependency: timm. Install timm to search ViT-Tiny."
            ) from exc
        timm = timm_module


def set_seed(seed: int, deterministic: bool = False) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def json_default(value):
    if hasattr(value, "item"):
        return value.item()
    if isinstance(value, Path):
        return str(value)
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def save_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, default=json_default)


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def clean_success_mask(series):
    if series.dtype == bool:
        return series

    numeric = pd.to_numeric(series, errors="coerce")
    if numeric.notna().any():
        return numeric.fillna(0).astype(int) == 1

    normalized = series.astype(str).str.strip().str.lower()
    return normalized.isin(["1", "true", "yes", "y"])


def resolve_image_path(raw_value, image_dir: Path) -> Path:
    raw_text = str(raw_value).strip()
    if not raw_text or raw_text.lower() == "nan":
        raise FileNotFoundError("Empty image path in CSV.")

    normalized = raw_text.replace("\\", "/")
    raw_path = Path(normalized)
    candidates: list[Path] = []

    if raw_path.is_absolute():
        candidates.append(raw_path)
    else:
        candidates.append(image_dir.parent / raw_path)

    candidates.append(image_dir / raw_path.name)

    if raw_path.suffix.lower() == ".png":
        candidates.append(image_dir / f"{raw_path.stem}.npy")
    elif raw_path.suffix.lower() == ".npy":
        candidates.append(image_dir / f"{raw_path.stem}.png")

    for candidate in candidates:
        if candidate.exists():
            return candidate

    searched = ", ".join(str(candidate) for candidate in candidates)
    raise FileNotFoundError(f"Image file not found. Searched: {searched}")


def load_image_array(path: Path):
    suffix = path.suffix.lower()
    if suffix == ".npy":
        image = np.load(path)
    else:
        with Image.open(path) as img:
            image = np.array(img.convert("RGB"))

    if image.ndim == 2:
        image = np.repeat(image[..., None], 3, axis=2)
    elif image.ndim == 3 and image.shape[0] in (1, 3) and image.shape[-1] not in (1, 3):
        image = np.moveaxis(image, 0, -1)

    if image.ndim != 3:
        raise ValueError(f"Unsupported image shape {image.shape} for {path}")

    if image.shape[-1] == 1:
        image = np.repeat(image, 3, axis=2)
    elif image.shape[-1] > 3:
        image = image[..., :3]

    image = image.astype(np.float32)
    if image.size and np.nanmax(image) <= 1.0:
        image = image * 255.0
    image = np.clip(image, 0.0, 255.0)
    return image


def preload_images_to_ram(dataframe, image_path_column: str):
    cache = []
    for idx, path in enumerate(dataframe[image_path_column].tolist(), start=1):
        cache.append(load_image_array(Path(path)))
        if idx % 5000 == 0:
            print(f"Loaded {idx:,} images into RAM")
    return cache


def make_dataset_class():
    class CachedLayoutRiskDataset(torch.utils.data.Dataset):
        def __init__(self, dataframe, image_cache, target_column, target_mean, target_std, transform):
            self.dataframe = dataframe.reset_index(drop=True)
            self.image_cache = image_cache
            self.targets = self.dataframe[target_column].astype(float).to_numpy()
            self.target_mean = float(target_mean)
            self.target_std = float(target_std)
            self.transform = transform

        def __len__(self):
            return len(self.dataframe)

        def __getitem__(self, idx):
            image = torch.from_numpy(self.image_cache[idx]).permute(2, 0, 1).float() / 255.0
            if self.transform is not None:
                image = self.transform(image)

            target = (self.targets[idx] - self.target_mean) / self.target_std
            target = torch.tensor(target, dtype=torch.float32)
            return image, target

    return CachedLayoutRiskDataset


def split_by_layout(dataframe, layout_column: str, seed: int):
    layout_ids = dataframe[layout_column].drop_duplicates().to_numpy()
    if len(layout_ids) < 3:
        raise ValueError("At least three unique layouts are required for train/val/test splits.")

    shuffled = layout_ids.copy()
    rng = np.random.RandomState(seed)
    rng.shuffle(shuffled)

    n_layouts = len(shuffled)
    n_train = int(0.8 * n_layouts)
    n_val = int(0.1 * n_layouts)

    if n_train < 1:
        n_train = 1
    if n_val < 1:
        n_val = 1
    if n_train + n_val >= n_layouts:
        n_train = max(1, n_layouts - 2)
        n_val = 1

    train_layouts = shuffled[:n_train]
    val_layouts = shuffled[n_train : n_train + n_val]
    test_layouts = shuffled[n_train + n_val :]

    train_df = dataframe[dataframe[layout_column].isin(train_layouts)].reset_index(drop=True)
    val_df = dataframe[dataframe[layout_column].isin(val_layouts)].reset_index(drop=True)
    test_df = dataframe[dataframe[layout_column].isin(test_layouts)].reset_index(drop=True)

    return train_df, val_df, test_df, train_layouts, val_layouts, test_layouts


def save_split_metadata(output_dir: Path, train_layouts, val_layouts, test_layouts) -> None:
    split_dir = output_dir / "splits"
    split_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame({"layout_id": train_layouts}).to_csv(split_dir / "train_layout_ids.csv", index=False)
    pd.DataFrame({"layout_id": val_layouts}).to_csv(split_dir / "val_layout_ids.csv", index=False)
    pd.DataFrame({"layout_id": test_layouts}).to_csv(split_dir / "test_layout_ids.csv", index=False)


def prepare_datasets(args, paths):
    csv_path, image_dir, output_dir = paths
    dataframe = pd.read_csv(csv_path)

    required_columns = [
        args.layout_column,
        args.image_column,
        args.target_column,
        args.clean_column,
    ]
    missing_columns = [column for column in required_columns if column not in dataframe.columns]
    if missing_columns:
        raise ValueError(f"CSV is missing required columns: {missing_columns}")

    clean_df = dataframe[clean_success_mask(dataframe[args.clean_column])].copy()
    clean_df = clean_df.reset_index(drop=True)
    if clean_df.empty:
        raise ValueError("No clean-success rows found.")

    clean_df["resolved_image_path"] = clean_df[args.image_column].apply(
        lambda value: str(resolve_image_path(value, image_dir))
    )

    train_df, val_df, test_df, train_layouts, val_layouts, test_layouts = split_by_layout(
        clean_df, args.layout_column, args.seed
    )
    save_split_metadata(output_dir, train_layouts, val_layouts, test_layouts)

    target_mean = float(train_df[args.target_column].astype(float).mean())
    target_std = float(train_df[args.target_column].astype(float).std())
    if not math.isfinite(target_std) or target_std <= 0:
        raise ValueError("Training target standard deviation must be positive.")

    save_json(
        output_dir / "target_stats.json",
        {
            "target_column": args.target_column,
            "target_mean": target_mean,
            "target_std": target_std,
            "clean_rows": int(len(clean_df)),
            "train_rows": int(len(train_df)),
            "val_rows": int(len(val_df)),
            "test_rows": int(len(test_df)),
            "train_layouts": int(len(train_layouts)),
            "val_layouts": int(len(val_layouts)),
            "test_layouts": int(len(test_layouts)),
            "split_seed": int(args.seed),
        },
    )

    print(f"Clean-success rows: {len(clean_df):,}")
    print(f"Train/val/test rows: {len(train_df):,} / {len(val_df):,} / {len(test_df):,}")
    print(f"Train target mean/std: {target_mean:.6f} / {target_std:.6f}")
    print("Preloading training images")
    train_cache = preload_images_to_ram(train_df, "resolved_image_path")
    print("Preloading validation images")
    val_cache = preload_images_to_ram(val_df, "resolved_image_path")

    transform = transforms.Compose(
        [
            transforms.Resize((args.resize_size, args.resize_size)),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )

    dataset_cls = make_dataset_class()
    train_dataset = dataset_cls(
        train_df,
        train_cache,
        args.target_column,
        target_mean,
        target_std,
        transform,
    )
    val_dataset = dataset_cls(
        val_df,
        val_cache,
        args.target_column,
        target_mean,
        target_std,
        transform,
    )

    return train_dataset, val_dataset, target_mean, target_std


def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)


def make_dataloader(dataset, batch_size: int, shuffle: bool, num_workers: int, seed: int, device):
    generator = torch.Generator()
    generator.manual_seed(seed)
    return torch.utils.data.DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=device.type == "cuda",
        persistent_workers=num_workers > 0,
        worker_init_fn=seed_worker if num_workers > 0 else None,
        generator=generator,
    )


def build_resnet18(hidden_dim: int, dropout: float, pretrained: bool):
    if pretrained:
        try:
            weights = models.ResNet18_Weights.IMAGENET1K_V1
            model = models.resnet18(weights=weights)
        except AttributeError:
            model = models.resnet18(pretrained=True)
    else:
        model = models.resnet18(weights=None)

    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Linear(in_features, hidden_dim),
        nn.ReLU(),
        nn.Dropout(dropout),
        nn.Linear(hidden_dim, 1),
    )
    return model


def build_vit_tiny(hidden_dim: int, dropout: float, pretrained: bool):
    model = timm.create_model("vit_tiny_patch16_224", pretrained=pretrained, num_classes=0)
    in_features = model.num_features
    model.head = nn.Sequential(
        nn.Linear(in_features, hidden_dim),
        nn.ReLU(),
        nn.Dropout(dropout),
        nn.Linear(hidden_dim, 1),
    )
    return model


def build_model(model_name: str, hidden_dim: int, dropout: float, pretrained: bool):
    if model_name == "resnet18":
        return build_resnet18(hidden_dim, dropout, pretrained)
    if model_name == "vit_tiny":
        return build_vit_tiny(hidden_dim, dropout, pretrained)
    raise ValueError(f"Unsupported model: {model_name}")


def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = 0.0
    total_count = 0

    for images, targets in loader:
        images = images.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        outputs = model(images).squeeze(-1)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_count += batch_size

    return total_loss / max(total_count, 1)


def denormalize(values, target_mean: float, target_std: float):
    return values * target_std + target_mean


def r2_score_np(y_true, y_pred) -> float:
    y_true = np.asarray(y_true, dtype=np.float64)
    y_pred = np.asarray(y_pred, dtype=np.float64)
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    if ss_tot <= 0:
        return float("nan")
    return float(1.0 - ss_res / ss_tot)


def evaluate(model, loader, criterion, device, target_mean: float, target_std: float):
    model.eval()
    total_loss = 0.0
    total_count = 0
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for images, targets in loader:
            images = images.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)

            outputs = model(images).squeeze(-1)
            loss = criterion(outputs, targets)

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_count += batch_size

            preds = denormalize(outputs.detach().cpu().numpy(), target_mean, target_std)
            true = denormalize(targets.detach().cpu().numpy(), target_mean, target_std)
            all_preds.append(preds)
            all_targets.append(true)

    y_pred = np.concatenate(all_preds)
    y_true = np.concatenate(all_targets)
    mae = float(np.mean(np.abs(y_true - y_pred)))
    r2 = r2_score_np(y_true, y_pred)

    return {
        "val_loss": total_loss / max(total_count, 1),
        "val_mae": mae,
        "val_r2": r2,
    }


def config_key(learning_rate: float, weight_decay: float) -> str:
    return f"{learning_rate:.12g}|{weight_decay:.12g}"


def run_single_config(
    model_name: str,
    learning_rate: float,
    weight_decay: float,
    train_loader,
    val_loader,
    args,
    device,
    target_mean: float,
    target_std: float,
):
    set_seed(args.seed, deterministic=args.deterministic)

    model = build_model(model_name, args.hidden_dim, args.dropout, args.pretrained).to(device)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=0.5,
        patience=args.scheduler_patience,
    )

    best = None
    best_val_loss = float("inf")
    epochs_without_improvement = 0
    history = []

    start_time = time.time()
    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device)
        metrics = evaluate(model, val_loader, criterion, device, target_mean, target_std)
        scheduler.step(metrics["val_loss"])

        current_lr = float(optimizer.param_groups[0]["lr"])
        record = {
            "epoch": epoch,
            "train_loss": train_loss,
            "val_loss": metrics["val_loss"],
            "val_mae": metrics["val_mae"],
            "val_r2": metrics["val_r2"],
            "learning_rate": current_lr,
        }
        history.append(record)

        print(
            f"[{model_name}] lr={learning_rate:g} wd={weight_decay:g} "
            f"epoch {epoch:02d}/{args.epochs} "
            f"train_loss={train_loss:.6f} val_loss={metrics['val_loss']:.6f} "
            f"val_mae={metrics['val_mae']:.4f} val_r2={metrics['val_r2']:.4f}"
        )

        if metrics["val_loss"] < best_val_loss - args.min_delta:
            best_val_loss = metrics["val_loss"]
            epochs_without_improvement = 0
            best = {
                "best_epoch": epoch,
                "best_val_loss": metrics["val_loss"],
                "best_val_mae": metrics["val_mae"],
                "best_val_r2": metrics["val_r2"],
            }
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= args.early_stop_patience:
            print(f"[{model_name}] Early stopping after epoch {epoch}.")
            break

    elapsed_seconds = time.time() - start_time
    if best is None:
        best = {
            "best_epoch": None,
            "best_val_loss": float("inf"),
            "best_val_mae": float("inf"),
            "best_val_r2": float("nan"),
        }

    result = {
        "model": model_name,
        "learning_rate": learning_rate,
        "weight_decay": weight_decay,
        "epochs_requested": args.epochs,
        "epochs_completed": len(history),
        "elapsed_seconds": elapsed_seconds,
        "history": history,
        **best,
    }

    del model
    if device.type == "cuda":
        torch.cuda.empty_cache()

    return result


def run_grid_search(
    model_name: str,
    learning_rates: list[float],
    weight_decays: list[float],
    train_dataset,
    val_dataset,
    args,
    device,
    target_mean: float,
    target_std: float,
    output_dir: Path,
):
    output_dir.mkdir(parents=True, exist_ok=True)
    results_path = output_dir / f"{model_name}_search_results.json"
    csv_path = output_dir / f"{model_name}_grid_search.csv"
    best_config_path = output_dir / f"{model_name}_best_config.json"

    if args.resume and results_path.exists():
        results = load_json(results_path)
        if not isinstance(results, list):
            raise ValueError(f"Expected a list of results in {results_path}")
        print(f"[{model_name}] Resuming from {results_path}")
    else:
        results = []

    completed = {
        config_key(float(result["learning_rate"]), float(result["weight_decay"]))
        for result in results
    }

    train_loader = make_dataloader(
        train_dataset,
        args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        seed=args.seed,
        device=device,
    )
    val_loader = make_dataloader(
        val_dataset,
        args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        seed=args.seed,
        device=device,
    )

    total_configs = len(learning_rates) * len(weight_decays)
    config_index = 0
    for learning_rate in learning_rates:
        for weight_decay in weight_decays:
            config_index += 1
            key = config_key(learning_rate, weight_decay)
            if key in completed:
                print(f"[{model_name}] Skipping completed config {config_index}/{total_configs}: {key}")
                continue

            print(
                f"[{model_name}] Running config {config_index}/{total_configs}: "
                f"lr={learning_rate:g}, wd={weight_decay:g}"
            )
            result = run_single_config(
                model_name,
                learning_rate,
                weight_decay,
                train_loader,
                val_loader,
                args,
                device,
                target_mean,
                target_std,
            )
            results.append(result)
            save_json(results_path, results)

    if not results:
        raise ValueError(f"No search results available for {model_name}.")

    ordered = sorted(
        results,
        key=lambda item: (
            float(item["best_val_loss"]),
            -float(item["best_val_r2"]) if math.isfinite(float(item["best_val_r2"])) else float("inf"),
        ),
    )
    summary_df = pd.DataFrame(ordered)
    summary_df = summary_df.drop(columns=["history"], errors="ignore")
    summary_df.to_csv(csv_path, index=False)

    best = ordered[0]
    best_config = {
        "model": model_name,
        "learning_rate": float(best["learning_rate"]),
        "weight_decay": float(best["weight_decay"]),
        "best_epoch": int(best["best_epoch"]),
        "best_val_loss": float(best["best_val_loss"]),
        "best_val_mae": float(best["best_val_mae"]),
        "best_val_r2": float(best["best_val_r2"]),
        "selection_metric": "lowest_validation_loss",
        "seed": int(args.seed),
        "epochs": int(args.epochs),
        "batch_size": int(args.batch_size),
        "hidden_dim": int(args.hidden_dim),
        "dropout": float(args.dropout),
        "pretrained": bool(args.pretrained),
    }
    save_json(best_config_path, best_config)

    print(f"[{model_name}] Best config saved to {best_config_path}")
    return best_config


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Run ResNet-18 and ViT-Tiny hyperparameter search for risk regression."
    )
    parser.add_argument("--data-dir", type=Path, default=Path("data/generated_dataset"))
    parser.add_argument("--csv-path", type=Path, default=None)
    parser.add_argument("--image-dir", type=Path, default=None)
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/hyperparameter_search"))
    parser.add_argument("--models", choices=["resnet18", "vit_tiny", "all"], default="all")

    parser.add_argument("--layout-column", default="layout_id")
    parser.add_argument("--image-column", default="layout_image_path")
    parser.add_argument("--target-column", default="invaded_grid_count")
    parser.add_argument("--clean-column", default="clean_success")

    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--resize-size", type=int, default=224)

    parser.add_argument(
        "--lr-values",
        type=parse_float_list,
        default=parse_float_list("1e-5,5e-5,1e-4,5e-4"),
    )
    parser.add_argument(
        "--weight-decay-values",
        type=parse_float_list,
        default=parse_float_list("1e-6,1e-5,1e-4"),
    )
    parser.add_argument("--early-stop-patience", type=int, default=5)
    parser.add_argument("--scheduler-patience", type=int, default=3)
    parser.add_argument("--min-delta", type=float, default=1e-8)

    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--dropout", type=float, default=0.3)
    parser.add_argument("--device", default=None)
    parser.add_argument("--deterministic", action="store_true")
    parser.add_argument("--no-pretrained", action="store_false", dest="pretrained")
    parser.add_argument("--no-resume", action="store_false", dest="resume")
    parser.set_defaults(pretrained=True, resume=True)
    return parser.parse_args(argv)


def resolve_paths(args):
    csv_path = args.csv_path if args.csv_path is not None else args.data_dir / "trial_summary_all.csv"
    image_dir = args.image_dir if args.image_dir is not None else args.data_dir / "layout_images"
    output_dir = args.output_dir
    return csv_path, image_dir, output_dir


def main(argv=None) -> int:
    args = parse_args(argv)
    model_names = ["resnet18", "vit_tiny"] if args.models == "all" else [args.models]

    load_libraries(require_timm="vit_tiny" in model_names)
    set_seed(args.seed, deterministic=args.deterministic)

    csv_path, image_dir, output_dir = resolve_paths(args)
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")
    if not image_dir.exists():
        raise FileNotFoundError(f"Image directory not found: {image_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)
    device = torch.device(args.device or ("cuda" if torch.cuda.is_available() else "cpu"))
    print(f"Using device: {device}")
    print(f"CSV: {csv_path}")
    print(f"Images: {image_dir}")
    print(f"Output: {output_dir}")

    train_dataset, val_dataset, target_mean, target_std = prepare_datasets(
        args,
        (csv_path, image_dir, output_dir),
    )

    best_configs = []
    for model_name in model_names:
        model_output_dir = output_dir / model_name
        best_config = run_grid_search(
            model_name,
            args.lr_values,
            args.weight_decay_values,
            train_dataset,
            val_dataset,
            args,
            device,
            target_mean,
            target_std,
            model_output_dir,
        )
        best_configs.append(best_config)

    summary_path = output_dir / "hyperparameter_search_summary.csv"
    pd.DataFrame(best_configs).to_csv(summary_path, index=False)
    save_json(output_dir / "hyperparameter_search_summary.json", best_configs)
    print(f"Search summary saved to {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
